actions:
  - on: 28943412-30b4-42cf-89d3-e1b33338c9d4
    rewards:
      - type: DISCORD_ROLE
        roles:
          - "822133505228013648"
  - on: 7ddc8f6b-a1d3-4f08-969c-e1fdd97c4a6b
    rewards:
      - type: FETCH
        config:
          url: http://localhost:1111
          method: POST
          data:
            broadcaster: "::BROADCASTER_ID::"
            redemption: "::REDEMPTION_ID::"
            reward_id: "::REWARD_ID::"
            user: "::USER_DATA::"
            user_input: "::USER_INPUT::"
